---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - install
    - openvswitch_switch

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package install openvswitch-switch'
  package:
    state: 'present'
    name: "{{package_name_openvswitch_switch}}"
    install_recommends: 'no'
  tags:
    - install
    - openvswitch_switch
