---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - disable
    - systemd_timesyncd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create timesyncd.conf'
  template:
    src: "{{file_src_timesyncd_conf}}"
    dest: "{{file_dst_timesyncd_conf}}"
    mode: "{{file_mode_timesyncd_conf}}"
    owner: "{{file_owner_timesyncd_conf}}"
    group: "{{file_group_timesyncd_conf}}"
  tags:
    - disable
    - systemd_timesyncd

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service stop systemd-timesyncd'
  service:
    state: 'stopped'
    enabled: 'no'
    name: "{{service_name_systemd_timesyncd}}"
  tags:
    - disable
    - systemd_timesyncd
