---

- name: 'task include enable'
  import_tasks: enable.yml
  when: (systemd_timesyncd_state is match('start|on|enable'))
  tags:
    - systemd_timesyncd

- name: 'task include disable'
  import_tasks: disable.yml
  when: (systemd_timesyncd_state is match('stop|off|disable'))
  tags:
    - systemd_timesyncd
