---

- name: 'task include install'
  import_tasks: install.yml
  when: not (apt_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - apt

- name: 'task include config'
  import_tasks: config.yml
  when: not (apt_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - apt
